### ISSUE TITLE
F454 , non riesco ad inserire le credenziali 

### ISSUE THREAD

**Issue by xman00007** [anotherjulien/MyHOME#11]
Salve, con il mio F454 , non riesco ad inserire le credenziali di accesso al F454 dal addon .. vanno inserite tramite .yaml ? grazie

**Comment by anotherjulien** [comment]
I don't speak Italian.

**Comment by xman00007** [comment]
Hi, with my F454, I can't enter the access credentials to the F454 from the addon .. must they be entered via .yaml? thanks

**Comment by bubez81** [comment]
Did you try to restart homeassistant one or two times?

**Comment by theBottinels** [comment]
check if your f454 as open connection (no authentication required) for some Ip range. If so disabled it.
