### ISSUE TITLE
Actions work, but updates stop working after some time

### ISSUE THREAD

**Issue by soloam** [anotherjulien/MyHOME#15]
Hello, I setup the integrations, and actions work ok, but the monitor stops working after some time, and I have to restart home assistant to get it working again. Anyone experienced this also?

**Comment by mougeat** [comment]
Hello, I have the same problem. I do not need to restart home assistant but to reload the My home integration.

I set up and automation to reload automatically every 30 sec and check the light states

`- id: '1619446400139'
  alias: Maintien connexion F454
  trigger:
  - hours: '*'
    minutes: '*'
    seconds: /30
    platform: time_pattern
  condition: []
  action:
  - service: rest_command.reload_f454
    data: {}
  - service: myhome.send_message
    data:
      message: '*#1*0##'
  mode: single`

with REST_COMMAND

`reload_f454:
    url: http://MY_HOMEASSISTANT_IP:PORT/api/config/config_entries/entry/INTEGRATION_ID/reload 
    method: POST
    headers:
      authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIwZThhNjg3ZTFlNTY0NmVjYmQ2NzdmMzU1OWUwNDM3ZCIsImlhdCI6MTYxMzI4Njg0NCwiZXhwIjoxOTI4NjQ2ODQ0fQ.PDhcsRc5rfjxQXx01HKGgK0z5YOFdZeE07sky14f1Q4'
      content-type: 'application/json'`

The INTEGRATION_ID can be find in the file \config\.storage\core.config_entries

I do not rememeber how I found the bearer sorry.

I hoppe this can help you.

**Comment by anotherjulien** [comment]
Hi Soloam, please provide the debug logs for Home Assistant during any occurrence of the problem.

**Comment by soloam** [comment]
Sorry, it was a problem in my setup! All seems ok now! Tks... If relevant again I'll open a new issue!

**Comment by anotherjulien** [comment]
Can I ask you what the problem was? Maybe it can be helpful to other people in the future!

**Comment by soloam** [comment]
Yes, my router was rebooting and I was losing connection, then it would not reconnect, maybe that should happen
