### ISSUE TITLE
Mh201 sometimes loose connection and reconnect

### ISSUE THREAD

**Issue by marcob79** [anotherjulien/MyHOME#16]
Sometimes it happen that command are not executed through my MH201, at first attempt, but if I retry it works.
Checking HA logs, I see some reconnections take place.
Maybe something to be improved in the connection management?
Please consider that the communication between HA and my MH201 is without WiFi, only Ethernet.

Thanks

This error originated from a custom integration.

Logger: custom_components.myhome
Source: /usr/local/lib/python3.9/site-packages/OWNd/connection.py:444
Integration: MyHome (documentation, issues)
First occurred: July 17, 2021, 4:38:56 PM (28 occurrences)
Last logged: 7:38:55 PM

Connection interrupted, reconnecting...

**Comment by anotherjulien** [comment]
This behavior is unfortunately more common for some gateway than others.
The error you see is already the remediation in place in case the gateway refuses the connection. It will try to reconnect multiple times with increasing time between tries.
At this point there is not much more I can do in the integration since the problem is on the gateway. :-( 
Some "older" models are more prone to this problem than others; but at the same time there is also a lot of behavior variation within the same model with different firmware. I also suspect there are multiple hardware revisions of the same model number throughout the years that also behave differently...

**Comment by caiosweet** [comment]
Yes correct.  Until version 7, disconnection occurred exactly every hour.  it was not a problem, but since version 8, it is constantly connecting / disconnecting ... today see to do debugging👍😇

**Comment by anotherjulien** [comment]
As tested with @caiosweet this bug should be solved with 0.8.1, setting the "concurrent command workers" to 1 by default

**Comment by marcob79** [comment]
Hi, thank you for your continue work in improving this component. It seems better but maybe i need some more hours to further confirm.
I was experiencing 4 new errors in log after restart that i don't understand what they are referred to, considering that i have an MH201 with just cover actuators.
one related to each of the following categories (that i don't have): binary sensor, sensor, switch and light

`Logger: homeassistant.components.binary_sensor
Source: custom_components/myhome/binary_sensor.py:116
Integration: Binary sensor (documentation, issues)
First occurred: 6:51:22 AM (1 occurrences)
Last logged: 6:51:22 AM

Error while setting up myhome platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/myhome/binary_sensor.py", line 116, in async_setup_entry
    _configured_binary_sensors = hass.data[DOMAIN][CONF][PLATFORM]
KeyError: 'binary_sensor'`

and

`Logger: homeassistant.components.sensor
Source: custom_components/myhome/sensor.py:98
Integration: Sensor (documentation, issues)
First occurred: 6:51:22 AM (1 occurrences)
Last logged: 6:51:22 AM

Error while setting up myhome platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/myhome/sensor.py", line 98, in async_setup_entry
    _configured_sensors = hass.data[DOMAIN][CONF][PLATFORM]
KeyError: 'sensor'`

and

`Logger: homeassistant.components.switch
Source: custom_components/myhome/switch.py:67
Integration: Switch (documentation, issues)
First occurred: 6:51:22 AM (1 occurrences)
Last logged: 6:51:22 AM

Error while setting up myhome platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/myhome/switch.py", line 67, in async_setup_entry
    _configured_switches = hass.data[DOMAIN][CONF][PLATFORM]
KeyError: 'switch'`

`Logger: homeassistant.components.light
Source: custom_components/myhome/light.py:73
Integration: Light (documentation, issues)
First occurred: 6:51:23 AM (1 occurrences)
Last logged: 6:51:23 AM

Error while setting up myhome platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/myhome/light.py", line 73, in async_setup_entry
    _configured_lights = hass.data[DOMAIN][CONF][PLATFORM]
KeyError: 'light'`

**Comment by anotherjulien** [comment]
Ah... Yes.
Thank you 😅 
I had noticed and fixed this for the climate entity because I don't have it myself, but I forgot to transpose the fix to the other platforms.
I've done that in the latest commit, it'll be part of the next release!

**Comment by marcob79** [comment]
Oh, you are so proactive!

How can I identify which kind of there message can cause this other error in the log?

`This error originated from a custom integration.

Logger: custom_components.myhome
Source: custom_components/myhome/gateway.py:103
Integration: MyHome (documentation, issues)
First occurred: 7:51:22 AM (93 occurrences)
Last logged: 6:51:22 PM

Data received is not a message: None`

**Comment by anotherjulien** [comment]
These are most likely messages that are present on the bus but not decoded properly by OWNd; I will need to work on OWNd to better handle messages that are completely unknown!

**Comment by anotherjulien** [comment]
Unfortunately, no logs will show them, not at this point.
I'll need to publish a new version of OWNd, I'll let you know!
