### ISSUE TITLE
Newcomer trying to move from OH to HA

### ISSUE THREAD

**Issue by fmalfatto** [anotherjulien/MyHOME#20]
Hello, all my home is based on BTICINO bus, plus some different other brands. I tried from years to manage the whole integration on rasperry PI (3 or 4). I started with Domoticz, then passed to Openhab, but none was covering the whole spread of devices, so I have to maintain both servers to have all features. Now I'm trying to learn HA too to verify if it gives more coverage, and I was able to install several Integrations, but I find none for MyHome. Is your addon suited for a MHS1 based plant? I also have a LN4890 non-official gateway to manage the 3486 alarm via AUX commands not supported from MHS1. I do not find any reference to BTICINO or MyHome or SCS in  the gui listof available integrations. How can I check it? TY in advance!

**Comment by anotherjulien** [comment]
Hi!
At the moment most major features are covered.
What is not covered is, notably, the burglar alarm system, sound diffusion and the video entry system.
I do not know what features you were missing from either Domoticz or Openhab, but feel free to try this component in HA.

This component is not built-in int HA but is available through a third party "installer" called HACS that first need to be installed in HA in order to then be able to install this MyHome component.

Overall, https://community.home-assistant.io is a great ressource to start your way into HA, and people there should be able to guide you on specific subject :-)

**Comment by fmalfatto** [comment]
TY anotherjulien, you are very kind. I was able to install HACS after several attempts and now I have your component active. Now I have only one big feature missing: I still use Domoticz only to engage/disengage the alarm system, not supported directly from MHS1. First I moved to OH waiting for that support, but after long time, own looks as freezed, so I'm looking around to see if there is some other way to have only one hub for all my devices. HA has all I need, and your development semms to be good and active. So I begin to learn it, I'm just signed on into the community and I'll follow there your job.

**Comment by anotherjulien** [comment]
How do you control your alarm with the LN4890 touch-screen and why is it not possible to do the same with MHS1?

**Comment by fmalfatto** [comment]
MHS1 acts as a "firewall" not allowing open commands to be forwarded to 3486. In domoticz I can have two gateways defined and concurrently active. MHS1 manages all devices, and  the touch has only the 3486 as enabled device.
On the 3486 are defined two open command thats when received do the actions of engaging/disengaging all zones ( I do not use partial engagement)

I followed these instruction in domoticz forum to read the 3486 status and to send open commands when status changes

https://www.domoticz.com/wiki/MyHome_OpenWebNet_Via_LAN_Interface
https://www.domoticz.com/forum/viewtopic.php?t=14053&start=40

> With bticino system myhome you can not directly control the alarm system with OpenWebNet protocol, but you can only monitor its status.
> 
> The only chance you have is to use the AUXILIARY devices, configuring your alarm control panel to run some commands (eg. Engage alarm)
> when it receives a particular OpenWebNet auxiliary command.
> 
> I have configured four auxiliaries in bticino alarm control panel, for example:
> - AUX 1 status 0 -> disengage
> - AUX 2 Status 1 -> engage with ALL zones
> - AUX 3 status 1 -> engage with partialization of zones 2 and 3
> - AUX 4 status 1 -> engage with partialization of zones 1 and 4
> 
> I then configured the auxiliary devices like push on or off button in domoticz.
> Here's an example to configure myhome alarm central 3486:
> 
> You must configure the automation through a special menu.
> Automations allow you to execute a OPEN command when a particular event occurs.
> In this case, the events are the changes of state of the auxiliary (who = 9), and the command are burglar alarm command (who=5).
> 
> Configuration Automation 1: when AUX-1 go OFF, then DISENGAGE all Zones
> Name: Disengaged all zones
> Event: command OPEN = *9*0*1##
> OPEN command to execute: *5*9##
> 
> Configuration Automation 2: when AUX-2 go ON, then ENGAGE active Zones
> Name: Engaged active zones
> Event: command OPEN = *9*1*2##
> OPEN command to execute: *5*8##
> 
> Configuration Automation 3: when AUX-3 go ON, then ENGAGE Zone 1 and Zone 4
> Name: Engaged zone 1 and zone 4
> Event: command OPEN = *9*1*3##
> OPEN command to execute: *5*8#14##
> 
> Then you can create 3 auxiliary devices in domoticz, first of type 'push OFF button' and the others of type 'push ON button'.
