### ISSUE TITLE
[Not an issue] Thank you!

### ISSUE THREAD

**Issue by bogdanm** [anotherjulien/MyHOME#21]
Hi, I have recently discovered this repository and it took me less than 20 minutes to finally integrate all my MyHOME devices into HomeAssistant. So far they're working without a glitch. I've been struggling to find a good way to integrate MyHOME into HA for a while now and I'm very glad that I found your repository, so I just wanted to say "thanks!".

**Comment by anotherjulien** [comment]
Thank you for your kind words, I'm like you like it and it works for you :-)
