### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by karel1980** [anotherjulien/MyHOME#23]
Hi there. I'm the author of https://github.com/karel1980/ReOpenWebNet
It seems we're both trying to build an open source solution for Homeassistant / MyHome/Openwebnet integration. Huzzah!

I'm wondering if you would be interested in an exchange of ideas :)

By the looks of it you're further along than I am in terms of functionally - I only have lights and dimmable lights at my disposal.
I'll certainly give your solution a try. My first attempt to do this in homeassistant was suffering a bit from my lack of asyncio programming knowledge :)

My current goal is to make all lights available in homeassistant without manually adding lights in a configuration yaml file. Just adding the mqtt addon and my in-progress mqtt bridge addon should be sufficient

**Comment by anotherjulien** [comment]
Hi!

Sure, I'm always open to exchange ideas :-)
Feel free to browse around in my code, if you have any questions I suppose the easiest way will be to find me on the Home Assistant community site!

If you find a proper way to bypass the need for a config file, I'm all ears, because for now every solution I think of hits a roadblock at one point or another :-/

**Comment by karel1980** [comment]
Great. I'll start experimenting with your homeassistant solution and go through the last couple of months on the forum, to see if I can help.

For bypassing the config file I was thinking of the following for lights (in my mqtt bridge solution):
If the bridge would send a configuration message to the homeassistant topic homeassistant/light/openwebnet/light{{where}}/config then all lights could magically appear in homeassistant.
I'll post a video if I get this to work.

Can you point out which roadblocks you are hitting specifically?

**Comment by karel1980** [comment]
My solution still requires a manual configuration of the openwebnet device, but that's something your solution has covered - very nice!
