### ISSUE TITLE
Can't add repository

### ISSUE THREAD

**Issue by bluegando** [anotherjulien/MyHOME#32]
When I try to add the url https://github.com/anotherjulien/MyHOME

to the add-on repositories I retrive this error:

`21-11-01 12:01:10 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/anotherjulien/MyHOME repository
21-11-01 12:01:11 ERROR (MainThread) [supervisor.store] https://github.com/anotherjulien/MyHOME is not a valid add-on repository
21-11-01 12:01:11 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / ee525a1c
21-11-01 12:01:11 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / ee525a1c`

Supervisor
Version
supervisor-2021.10.8

Core
Version
core-2021.11.0b3

**Comment by anotherjulien** [comment]
Did you add the repository to HACS?
Because that's not what your logs seem to suggest.
