### ISSUE TITLE
Cover:  advanced: False

### ISSUE THREAD

**Issue by gabrieledaltoe** [anotherjulien/MyHOME#36]
Hi!
I have this configuration.....

porta_studiolo_tapp:
      where: "72"
      name: Tapparella Porta Studiolo
      advanced: False
      manufacturer: Legrand
      model: 6457

But current_position of cover.tapparella_porta_studiolo is 92 and his state is "open".
I have another cover and his state is unkown but there isn't a current_position attribute.

Many days before I had this configuration

porta_studiolo_tapp:
      where: "72"
      name: Tapparella Porta Studiolo
      advanced: True
      manufacturer: Legrand
      model: 6457

But now I don't want to track current position of my cover...
How can I change the configuration to ignore the "current_position" so that the state becomes "unknow"?
Thanks

**Comment by anotherjulien** [comment]
Thinking about it, I assume you'll need to remove the entity entirely and restart HA for the integration to recreate it from scratch.
You'll loose all history for the entity, but then again, the entity's history is the reason you're facing this issue I think.
