### ISSUE TITLE
the shutters does not work in homekit

### ISSUE THREAD

**Issue by giannimp** [anotherjulien/MyHOME#4]
the shutters does not work in homekit, lights work!

**Comment by anotherjulien** [comment]
Do the shutters work in Home Assistant, outside Homekit?

**Comment by anotherjulien** [comment]
No answers.

**Comment by monsterciattolo** [comment]
in home assistant all works fine.
I tried to export shutters from home assistant to homekit.
I'm able to use function up, down and stop but on homekit i can only open and close. 
if i click on shutters during the closing or opening, shutter continues the closing or opening without stop or opening.

**Comment by anotherjulien** [comment]
This integration is the interface between MyHome SCS bus and Home Assistant.
As long as it functions properly in Home Assistant, then the integration is doing its job correctly.

If you have a problem with HomeKit, Google Home, Alexa or any such thing, then you might want to open an issue with the relevant developers of those integrations.
