### ISSUE TITLE
deprecated `async_get_registry`

### ISSUE THREAD

**Issue by marcob79** [anotherjulien/MyHOME#52]
After upgrade to home assistant 2022.6.2 i can notice the following warning in logs 

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: June 5, 2022, 7:07:53 PM (3 occurrences)
Last logged: June 5, 2022, 7:07:53 PM

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for myhome using this method at custom_components/myhome/__init__.py, line 89: device_registry = await hass.helpers.device_registry.async_get_registry()
Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for myhome using this method at custom_components/myhome/__init__.py, line 159: entity_registry = await hass.helpers.entity_registry.async_get_registry()
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for myhome using this method at custom_components/myhome/__init__.py, line 160: device_registry = await hass.helpers.device_registry.async_get_registry()

**Comment by caiosweet** [comment]
Hi, This should already be fixed if you use version master. #51
Anyway, for now it's just a warning: 0)
