### ISSUE TITLE
Manual Gateway Entry unknown error

### ISSUE THREAD

**Issue by jeffstxiao** [anotherjulien/MyHOME#54]
Hi,

I have two gateways in the house on two separate BUS, one is a scheduler which was auto discovered and I have set up which is running perfectly, but my MHS1 isn’t found but when I try manual gateway entry it shows “unknown error occurred”. Not sure how to fix thanks!!

**Comment by anotherjulien** [comment]
No fix, sorry.
Multiple gateways are not supported and never will be.
You can use either bus/gateway but cannot integrate both.
