### ISSUE TITLE
MHServer1 not discovered

### ISSUE THREAD

**Issue by Punch1981** [anotherjulien/MyHOME#56]
Hello, 
if my mhserver1 is not detected being under switch in the same network 
how can I force it knowing the ip?
firmware version 2.60.65
Thanks
Giulio

**Comment by anotherjulien** [comment]
Yes, if you add the integration manually from the "Integration" page, it'll first search for a gateway and you'll have the option to add a custom one.

**Comment by Punch1981** [comment]
the problem is that trying to insert in the integration page it tells me that All the MyHome gateways are already configured, 
I was wondering if you could force the server's IP in some way
at the moment in the same network with fixed ip he does not see it, but on myhome up everything works

Giulio

**Comment by anotherjulien** [comment]
Can you try to reinstall the current master?
The "all gateways already configured" has been fixed in a796469ffd3958ddf2778e7d6a464b43307c8f97
You should be able to add a custom one.

**Comment by Punch1981** [comment]
ok to fix a796469
now he offers me custom
but by entering the data it gives me

Manual gateway entry
Fill out the information for your gateway

Unknown error occurred
IP address
192.168.1.70
Port
20000
MAC address
00:03:50:87:18:94
Device type
MyHomeServer1

ip port and mac detected by router and connected with MyHome suite
I also tried to reset the gateway from myhome up but I don't detect it anyway ...

**Comment by anotherjulien** [comment]
Do you maybe have any logs to share?
