### ISSUE TITLE
unable to see Automation (cover) events

### ISSUE THREAD

**Issue by marcob79** [anotherjulien/MyHOME#60]
I had a setup with an MH201 gateway and some covers that is working like a charm.
I was trying to further improve my setup by tring to intercept cover events that comes from physical button pression

`3 types of cover events exist:

myhome_general_automation_event
myhome_area_automation_event
myhome_group_automation_event
All events have an attribute message containing the raw OpenWebNet message and an attribute event that can be either open, close or stop.
Area events also have an attribute area containing the area ID (the 'A' of the 'APL'); and Group events have an attribute group containing the group ID (without the leading #).`

after listening on home assistant events like myhome* I'm not able to see them at all, neither pressing the single cover, nor pressing the general cover button

**Comment by anotherjulien** [comment]
I don't have a general cover button configured at home.
However, I have a couple of group ones, and listening to `myhome_group_automation_event` works just fine.

**Comment by marcob79** [comment]
I will try again.
Is there a way to get the single cover button pressed event?

**Comment by Technologiezentrum** [comment]
I have the same problem. I tried all thre types of cover events with the listener. While listening, I press some cover buttons but no event is fired.
