### ISSUE TITLE
Support for audio control / sound system (WHO 16)?

### ISSUE THREAD

**Issue by fampi2002** [anotherjulien/MyHOME#66]
Does anyone have experience with audio control/sound system – I mean device type WHO 16?
Is it even possible to integrate my radio and speakers using the code from anotherjulien? If so, how does it work? If not, maybe someone can tell me whether this device type is supported in the future?

**Comment by anotherjulien** [comment]
WHO 16 is not supported and I will not contribute any code towards it.
If someone wants to try, they're welcome to do so.
