### ISSUE TITLE
Find the password used in previous installation

### ISSUE THREAD

**Issue by wh33li3** [anotherjulien/MyHOME#70]
Hey julien I have used your custom component in the past to control my home gateway, I'm trying to migrate to a fresh home assistant installation. I cannot seem to remember the password used for accessing the  MyHomeserver1 is there anyway I can get it from the old Homeassistant server? in the yaml I only have my standard configuration.

**Comment by anotherjulien** [comment]
Sorry, no real way to do this easily.
Maybe by digging around in `/config/.storage/core.device_registry` or `/config/.storage/core.config_entries`?
