### ISSUE TITLE
Open cover while closing and vice versa

### ISSUE THREAD

**Issue by ermanno00** [anotherjulien/MyHOME#72]
When I try to raise a rolling shutter while it is closing or vice versa, it is simply stopped. I fixed it by editing the cover.py file like this.

<img width="622" alt="Senza titolo" src="https://user-images.githubusercontent.com/80400985/219093001-e2bbe654-68db-42dd-bbef-24ec65cfc848.png">

**Comment by FOSV** [comment]
It depends on which actuator you have, specifically there are two:

- **Basic (F411U2)**: Cannot handle partial opening/closing. When you give the opposite command to what it is doing (i.e.: the curtain is lowering and you send the command to raise it) it stops the curtain.

- **Advanced (F401)**: It can handle partial openings/closures. When you give the opposite command to what he is doing (i.e.: the curtain is lowering and you send the command to raise it) he executes exactly the command you gave him.

**Comment by ermanno00** [comment]
My actuators are L4671/2. I think they are "Basic", but regardless of the partial opening/closing, if I want to close the shutter while it is opening, why should it just stop?

**Comment by anotherjulien** [comment]
What happens in this scenario when you use your wall switches?
For me it does just that, stop.

**Comment by ermanno00** [comment]
When i try to close from wall switch while opening it stops, so i re-click and it closes. You are right. But, on the wall switch, I don't have a stop button, only "open" and "close" "actions", which became "stop" if the curtain is moving. In home assistant, i have three action behind a cover entity: open, close and stop. 

So it is semantically correct that the open action opens in any case (even if it is closing), the close action ditto and the stop action (as it already does) always interrupts.

**Comment by ermanno00** [comment]
But the problem is easily "solvable" with the solution I propose. If you deem it invalid adding it to the mail branch does nothing, I'll keep it for my environment

**Comment by anotherjulien** [comment]
My point was that the integration is correctly reproducing the behavior of the product.
The need to be able to open covers with one single click while they are closing or vice-versa might be rather specific to you.
Your problem is with MyHome as a system, and if you want this functionality, using [template entities](https://www.home-assistant.io/integrations/cover.template/) with custom open/close scripts might be a better way forward.
