### ISSUE TITLE
INSTALLATION ERROR Configartion file "/config/myhome.yaml" is not present! Home Assistant 2023.2.5

### ISSUE THREAD

**Issue by bensosys** [anotherjulien/MyHOME#73]
After installation this error occour. Is there compatibility issue on new HA update? In previous realeses there was no problem.
NOTE: this installation is supervised previous was DOCKER installation.

**Comment by anotherjulien** [comment]
You must have installed the master branch.
It is currently hosting the release candidate of version 0.9 which uses a different configuration structure.
You can find all the necessary information for this in the project's [wiki](https://github.com/anotherjulien/MyHOME/wiki/Configuration)
