### ISSUE TITLE
MyHome 0.9.0 - new configuration extra entities

### ISSUE THREAD

**Issue by Depechie** [anotherjulien/MyHOME#79]
Not really an issue, but a question about the new config.
Everything is working fine, all my lights and switches are working... But after implementing the new config structure and the MyHome 0.9.0 addin, all my lights now have 2 extra new entities. An turn on and turn off. Besides the actual light entity itself.

Is this expected behaviour? And if so, what is the purpose?

**Comment by caiosweet** [comment]
I report here what Julien wrote in the forum

https://community.home-assistant.io/t/legrand-bticino-myhome/229337/888?u=caiosweet

It uses WHO 14 commands to disable (lock) or enable (unlock) the commands.
That means that when a light is locked, nothing you do will change it, not with Home Assistant, not with OpenWebNet, not with your wall switches.

**Comment by Depechie** [comment]
ha thx @caiosweet for the details! Did not know this was possible...
