### ISSUE TITLE
No version key in manifest

### ISSUE THREAD

**Issue by monsterciattolo** [anotherjulien/MyHOME#8]
Hi Anotherjulien,
many thanks for your intergration and i spent a lot of time to find something similar.
Thanks god you create this addon.

I want to highlight the warning message below.

2021-03-26 21:07:23 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'myhome'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'myhome'

Then you miss the link to project documentation on documentation in home assistant - integration - myhome - documentation

again good job!
M.

**Comment by anotherjulien** [comment]
Hi !
This should already be fixed if you use version 0.7.4 (which is the latest to this date) or master.

**Comment by caiosweet** [comment]
> Hi !
> This should already be fixed if you use version 0.7.4 (which is the latest to this date) or master.

Hi Julien, just to say that...
after this new option(versione in manifest), hacs messed around a bit.  
To get update notifications again, the component must be uninstalled and reinstalled manually from the hacs repositories 👍👍
