### ISSUE TITLE
Missing configuration file

### ISSUE THREAD

**Issue by nemod79** [anotherjulien/MyHOME#81]
Dear, I recently installed your integration via HACS in a docker configuration.
I was simply not able to complete any configuration, the integration was not providing by default the myhome.yaml file.

Even creating it manually the integration was able to read the file but not able to write it.

User permission are just fine. Let me know which informations you need for debugging and how can I support you on this.
Thank you

**Comment by anotherjulien** [comment]
The integration does not write anything in the file.
The writing is up to you.

**Comment by nemod79** [comment]
Dear, thank you. And what about password config and IP, where are they stored ? I've the doubt that is not storing them correctly as per my MHS1.  Il 1 apr 2023 18:07, anotherjulien ***@***.***> ha scritto:
The integration does not write anything in the file.
The writing is up to you.

**Comment by anotherjulien** [comment]
This is part of the config entry for the gateway, this is stored by Home Assistant itself (not the integration) in `/config/.storage/core.config_entries`.
Note that this is *not* a file you want to edit manually.
If you want to see the current password, just go to the integrations page in Home Assistant and click "configure" on your gateway entry.
