### ISSUE TITLE
F522

### ISSUE THREAD

**Issue by zane75** [anotherjulien/MyHOME#9]
hi my name is marco, thank you very much for the great work, my f522 marks zero consumption.  I have asked in various forums and read others with this problem.

**Comment by anotherjulien** [comment]
Hi,

Discussing with another user who has F522 on the Home Assistant forum, it seems they simply do not have the functionality to return instant power usage.
Only F520 and F521 seem to be able to do that.

**Comment by zane75** [comment]
thanks for the answer, I asked the author of the Botticino iOS app that can display consumption.  he replied with this code * # 18 * Where * 113 ##, I don't understand much about it, hope it can help

Zanellato Marco

**Comment by zane75** [comment]
*#18*Where*113##

**Comment by anotherjulien** [comment]
Can you post debug logs from Home Assistant?
Is their <WHERE> address like 5[1-255] or like 7[1-255]#0?

Maybe F522 reply to *#18*<WHERE>*113##, but they need to be able to reply to *#18*<WHERE>*#1200#1*<DURATION>##. If not, they cannot send their active power autonomously, you would need to interrogate them every few seconds for it to make any sense; and don't believe it is something realistic.

**Comment by zane75** [comment]
I don't know how to do it in home assistance, now I try to understand, but in the terminal it returns * # 18 * 71 # 0 * 113 * 17 ##


Zanellato Marco

> Il giorno 27 mar 2021, alle ore 17:21, anotherjulien ***@***.***> ha scritto:
> 
> Can you post debug logs from Home Assistant?
> Is their address like 5[1-255] or like 7[1-255]#0?
> 
> Maybe F522 reply to #18113##, but they need to be able to reply to #18#1200#1*##. If not, they cannot send their active power autonomously, you would need to interrogate them every few seconds for it to make any sense; and don't believe it is something realistic.
