### ISSUE TITLE
MyHome: Failed to set up

### ISSUE THREAD

**Issue by mr-frnk** [anotherjulien/MyHOME#93]
Hi All, 

Need some help to get the MyHome integration setup/working. 

When opening the integration you can already see the ‘Failed to set up’ error

<img width="345" alt="Pasted Graphic" src="https://github.com/anotherjulien/MyHOME/assets/10833913/0b6fbae6-ce06-44ea-ae53-c57ee91493bb">

After ‘updating the configuration (see screenshot below) the following error message is written to the logs

2023-08-17 20:46:23.175 ERROR (MainThread) [frontend.js.latest.202308020] http://192.168.1.3:8123/frontend_latest/15664-mac7RvTTaE0.js:1:78491 TypeError: null is not an object (evaluating 'this.contentElement.removeEventListener')

<img width="407" alt="Screenshot 2023-08-17 at 20 49 24" src="https://github.com/anotherjulien/MyHOME/assets/10833913/31fd55c0-2d0f-4321-a199-5972eff66fc9">

I suspect the error  caused by something in the my home.yaml file. The file file is in the right location, and also IP address and Password are correct.  

<img width="707" alt="Pasted Graphic 1" src="https://github.com/anotherjulien/MyHOME/assets/10833913/a68beccf-e969-47df-8eac-20486cafe2ee">

Does anyone has any idea what the problem could be or how to troubleshoot this issue? 

Regards, 
Franky

**Comment by stijn001** [comment]
As far as I know, all bTicino MAC addresses start with 00:03:50... not 00:30:50

**Comment by mr-frnk** [comment]
@stijn001 Can't believe the solution was that simple. 
Thanks a lot for your help
