### ISSUE TITLE
Classe EOS300

### ISSUE THREAD

**Issue by arhisa2021** [anotherjulien/MyHOME#95]
Hi, 
I'm new to almost everything (bticino environment and home assistant). :)
I have a question...I noticed that all of threads are mentioned in collaboration with SCS Myhomeserver... However the new way of Bticino is with EOS300 and no need for SCS server. Now I have my first problem. I have installed MyHome integration into HomeAssistant, but when I'm trying to setup default gateway in my scenario this should be EOS300. I've setup EOS300 into same network as HA, but getting error when trying to add manual gateway entry. IP and MAC is OK and it is EOS300. port is still as default 20000... Here I'm unsure of Device Type.

Has anyone ever tried to integrate Bticino MyHome with EOS300?
Thank you all
BR
Rok

**Comment by Johnnytrapano** [comment]
Hi, here same issue!

**Comment by anotherjulien** [comment]
This integration does not work for "with Netatmo" stuff, and it never will.
It is only for SCS gateways.

It is very poor marketing from Legrand to have multiple incompatible product lines with the same name...
